### ISSUE TITLE
Incorrect license specified for the filesystem library

### ISSUE THREAD

**Issue by gulrak** [conda-forge/cpp-filesystem-feedstock#6]
Issue:

The file `recipe/meta.yaml` specifies `BSD` as the license of `https://github.com/gulrak/filesystem/archive/v1.3.4.tar.gz` but the library was released unter `MIT` license starting with the release of v1.3.0.

**Comment by JohanMabille** [comment]
My bad, sorry for that error.

**Comment by gulrak** [comment]
No problem, just wanted to inform you. Thanks for the quick reaction!
